spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: root

  sql:
    init:
      dataLocations: classpath:/movie_service.sql
      
   zipkin:
    base-url: http://localhost:9411/
    enabled: true
    
   rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  movie:
    name: MovieQueue
server:
    port: 8081
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
